name: custody_rx
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  http: ^1.1.0                 #this library is used to make http requests
  floor: ^1.4.2
  get_it: ^7.6.4               #this library is used to implement the service locator pattern
  dartz: ^0.10.1
  equatable: ^2.0.5       
  flutter_bloc: ^8.1.3         #this library is used to implement the bloc pattern
  fluttertoast: ^8.2.4            
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.3.1    #this library is used to log messages
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Medium.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans_Condensed-Bold.ttf
        # - asset: OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
